algoritmo "MediaDaNotaDeUmAluno"
var
nome:caractere
n1,n2,n3,n4,media:real
inicio
//entrada
escreval("Digite o nome do aluno")
leia(nome)
escreval("Digite a primeira nota")
leia(n1)
escreval("Digite a segunda nota")
leia(n2)
escreval("Digite a terceira nota")
leia(n3)
escreval("Digite a quarta nota")
leia(n4)
//processamento
media <- (n1+n2+n3+n4)/4
//saida
escreval("A media do aluno é",media)
fimalgoritmo
